# Generated by Django 3.1 on 2020-09-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='menu_item_1.jpg', unique=True, upload_to='category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseproducts',
            name='image',
            field=models.ImageField(unique=True, upload_to='images'),
        ),
    ]
