# Generated by Django 3.1 on 2020-09-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200914_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproducts',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
