# Generated by Django 3.1 on 2020-09-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='bread.jpg', upload_to='category'),
            preserve_default=False,
        ),
    ]
