# Generated by Django 3.1 on 2020-09-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Subject',
            field=models.CharField(default='franchise', max_length=30),
            preserve_default=False,
        ),
    ]
