# Generated by Django 3.1.1 on 2020-10-03 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contact_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('desc', models.TextField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.AddField(
            model_name='baseproducts',
            name='desc',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='baseproducts',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='catlog', to='home.category'),
        ),
        migrations.AlterField(
            model_name='baseproducts',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='baseproducts',
            name='slug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sug', to='home.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
